# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Adam Erispaha
tagline:          'A blog'
description:      'Civil/environmental engineer, loves charts, data, urban hydrology, and Python'
url:              https://www.adamerispaha.com
# baseurl:          /
baseurl:          ""

author:
  name:           'Adam Erispaha'
  url:            https://twitter.com/adamerispaha

paginate:         3

# Custom vars
version:          2.1.0

github:
  account:        https://github.com/aerispaha
  gist:           https://gist.github.com/aerispaha

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb
